### ISSUE TITLE
nxos-ssh get_mac_address_table on n3k

### ISSUE THREAD

**Issue by seismiccollision** [napalm-automation/napalm-nxos#146]
### Description of Issue/Question
nxos-ssh errors on "show mac address-table" on n3k
```
>>> device.get_mac_address_table()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user1/.local/lib/python2.7/site-packages/napalm_nxos_ssh/nxos_ssh.py", line 1335, in get_mac_address_table
    else:
ValueError: Unexpected output from: u'G    2     0000.0c07.ac01   static   -         F      F    Po1(R)'
```

I think it has something to do with the leading "G" and tried to sort it out myself but turned out to be beyond me for now

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[x] Yes
[ ] No

### napalm-nxos version
(Paste verbatim output from `pip freeze | grep napalm-nxos` between quotes below)

```
napalm-nxos==0.7.0
```

### NX-OS version
(Paste verbatim output from `show version | json` between quotes below)

```
{"header_str": "Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nCopyright (C) 2002-2016, Cisco and/o
r its affiliates.\nAll rights reserved.\nThe copyrights to certain works contained in this software are\nowned by other third parties and 
used and distributed under their own\nlicenses, such as open source.  This software is provided \"as is,\" and unless\notherwise stated, t
here is no warranty, express or implied, including but not\nlimited to warranties of merchantability and fitness for a particular purpose.
\nCertain components of this software are licensed under\nthe GNU General Public License (GPL) version 2.0 or \nGNU General Public License
 (GPL) version 3.0  or the GNU\nLesser General Public License (LGPL) Version 2.1 or \nLesser General Public License (LGPL) Version 2.0. \n
A copy of each such license is available at\nhttp://www.opensource.org/licenses/gpl-2.0.php and\nhttp://opensource.org/licenses/gpl-3.0.ht
ml and\nhttp://www.opensource.org/licenses/lgpl-2.1.php and\nhttp://www.gnu.org/licenses/old-licenses/library.txt.", "bios_ver_str": "3.4.
0", "kickstart_ver_str": "7.0(3)I2(2e)", "bios_cmpl_time": "08/07/2015", "kick_file_name": "bootflash:///nxos.7.0.3.I2.2e.bin", "kick_cmpl
_time": "6/19/2016 2:00:00", "kick_tmstmp": "06/19/2016 09:26:38", "chassis_id": "Nexus 3048 Chassis", "cpu_name": "Intel(R) Celeron(R) CP
U        P4505  @ 1.87GHz", "memory": "3903880", "mem_type": "kB", "proc_board_id": "FOC17457MFS", "host_name": "3048-1", "bootflash_size"
: "1880320", "slot0_size": "0", "kern_uptm_days": "431", "kern_uptm_hrs": "21", "kern_uptm_mins": "19", "kern_uptm_secs": "3", "rr_usecs":
 "786149", "rr_ctime": "Wed Aug 10 18:34:01 2016", "rr_reason": "Reset Requested by CLI command reload", "rr_sys_ver": "7.0(3)I2(2e)", "rr
_service": null, "manufacturer": "Cisco Systems, Inc."}
```

### Steps to Reproduce the Issue
here is what 'show mac address-table' gets:
```
Legend: 
        * - primary entry, G - Gateway MAC, (R) - Routed MAC, O - Overlay MAC
        age - seconds since last seen,+ - primary entry using vPC Peer-Link,
        (T) - True, (F) - False
   VLAN     MAC Address      Type      age     Secure NTFY Ports
---------+-----------------+--------+---------+------+----+------------------
*    2     0000.0c07.ac01   dynamic  0         F      F    Eth1/51
*    2     f44e.0583.0d41   dynamic  0         F      F    Eth1/51
*  111     0000.0c07.ac01   dynamic  0         F      F    Eth1/51
*  111     f44e.0583.0d41   dynamic  0         F      F    Eth1/51
*  112     aaaa.bbbb.cccc   dynamic  0         F      F    Eth1/51
G    2     0000.0c07.ac01   static   -         F      F    Vlan2(R)
G  111     0000.0c07.ac01   static   -         F      F    Vlan111(R)
G    -     f8c2.889b.02bc   static   -         F      F    sup-eth1(R)
G    2     f8c2.889b.02bc   static   -         F      F    sup-eth1(R)
G  111     f8c2.889b.02bc   static   -         F      F    sup-eth1(R)
G  112     f8c2.889b.02bc   static   -         F      F    sup-eth1(R)
```

here is what i ran in napalm:
```
import napalm
import napalm_nxos_ssh

host='172.16.1.1'
user='admin'
passwd='admin'

driver = napalm.get_network_driver('napalm_nxos_ssh')
device = driver(hostname=host, username=user, password=passwd)
device.open()
device.get_mac_address_table()
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user1/.local/lib/python2.7/site-packages/napalm_nxos_ssh/nxos_ssh.py", line 1335, in get_mac_address_table
    else:
ValueError: Unexpected output from: u'G    2     0000.0c07.ac01   static   -         F      F    Po1(R)'
```

**Comment by ktbyers** [comment]
@seismiccollision I think this issue with parsing the Gateway Mac is fixed in the develop branch already (as I fixed it recently).

Can you test the `develop` branch and see if you still are seeing this issue.

**Comment by seismiccollision** [comment]
@ktbyers you are indeed correct! my bad and thanks for the help!

**Comment by ktbyers** [comment]
@seismiccollision No worries at all...it was just recently fixed.
