### ISSUE TITLE
Error when retrieving facts

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-nxos#40]
### Description of Issue/Question

Unable to retrieve facts
### napalm-nxos version

(Paste verbatim output from `pip freeze | grep napalm-nxos` between quotes below)

0.3.0
### NX-OS version

(Paste verbatim output from `show version | json` between quotes below)

7.3(0)N1(1)
### Steps to Reproduce the Issue

Execute `get_facts`
### Error Traceback

(Paste the complete traceback of the exception between quotes below)

```
>>> e.get_facts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm-nxos/napalm_nxos/nxos.py", line 199, in get_facts
    facts_dict = nxapi_lib.get_facts(self.device)
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/pycsco/nxos/utils/nxapi_lib.py", line 2391, in get_facts
    xml = device.show(command)
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/pycsco/nxos/device.py", line 114, in show
    data_dict = xmltodict.parse(data[1])
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 489, column 29
```

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-nxos/pull/41
