### ISSUE TITLE
napalm-nxos replace_config / compare_config generating exception

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#51]
Config should have had no changes.

The following error occurred on NX-OSv

```
Traceback (most recent call last):
  File "test_nxos_cfg.py", line 46, in <module>
    print device.compare_config()
  File "/home/kbyers/applied_python/local/lib/python2.7/site-packages/napalm_nxos/nxos.py", line 205, in compare_config
    messy_diff = install_config.get_diff(self.device, self.fc.dst)
  File "/home/kbyers/applied_python/local/lib/python2.7/site-packages/pycsco/nxos/utils/install_config.py", line 14, in get_diff
    '#Generating Rollback Patch')[1].replace(
IndexError: list index out of range
```

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-nxos/commit/0bd7f01cec53a3f5b9f1c96e04eef9191fb6132c
