### ISSUE TITLE
ssl._create_unverified_context fails if Python version < 2.7.9

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#54]
```
>>> from napalm import get_network_driver
>>> driver = get_network_driver('nxos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cisco/.virtualenvs/nap-test/local/lib/python2.7/site-packages/napalm_base/__init__.py", line 96, in get_network_driver
    module = importlib.import_module(module_install_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cisco/.virtualenvs/nap-test/local/lib/python2.7/site-packages/napalm_nxos/__init__.py", line 22, in <module>
    from nxos import NXOSDriver  # noqa
  File "/home/cisco/.virtualenvs/nap-test/local/lib/python2.7/site-packages/napalm_nxos/nxos.py", line 49, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'
>>> 
```

**Comment by ktbyers** [comment]
```
ssl._create_unverified_context is present in Python 2.7.9 and later. If you can get a hold of a later Python, that should solve your problem.
```

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-nxos/commit/0bd7f01cec53a3f5b9f1c96e04eef9191fb6132c
